---
containerPorts:   # has to match hostPorts when useHostNetwork is true
  kafka: 9092

config: |
  global
    log stdout format raw local0
    maxconn 1024

  defaults
    log global
    timeout client 60s
    timeout connect 60s
    timeout server 60s

  frontend kafka-listener
    mode tcp
    bind :9092
    default_backend kafka-upstream

  backend kafka-upstream
    mode tcp
    balance leastconn
    server kafka-proxy kafka-proxy:9092 check send-proxy-v2
