---
apiVersion: v1
kind: Service
metadata:
  name: kafka-proxy
  namespace: kakfa-proxy
  labels:
    app.kubernetes.io/name: kafka-proxy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kafka-proxy
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-proxy
  namespace: kafka-proxy
  labels:
    app.kubernetes.io/name: kafka-proxy
  annotations:
spec:
  minReadySeconds: 0
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-proxy
    spec:
      # terminationGracePeriodSeconds: 60
      # dnsPolicy: ClusterFirst
      volumes:
        - name: haproxy-config
          configMap:
            name: release-name-haproxy
      containers:
        - name: kafka-proxy
          image: ghcr.io/limoges/kafka-proxy:ppv2@sha256:db507dd4fb55d16b13ae639b76e2b51c005ac32be381cae2399f17a616bab14a
          imagePullPolicy: IfNotPresent
          args:
            - 'server'
            - '--bootstrap-server-mapping'
            - 'pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092,0.0.0.0:9092'
            - '--dynamic-advertised-listener'
            - 'b{{.brokerId}}.brokers.kafka-main.fleet.dev.eu-west-1.sumup.net:9092'
            - '--dynamic-listeners-disable'
            - '--tls-enable'
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
            - name: kafka
              containerPort: 9092
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
